language: go
sudo: false
go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - master

matrix:
  fast_finish: false
  include:
  - go: 1.11.x
    env: GO111MODULE=on
  - go: 1.12.x
    env: GO111MODULE=on

install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; else go get -t -v ./...; fi

