language: go
go:
- 1.10.x

matrix:
  include:
  - go: "1.11.x"
    before_script:  go mod vendor
    script: go test -v -mod=vendor ./...
  - go: "1.12.x"
    before_script:  go mod vendor
    script: go test -v -mod=vendor ./...

env:
- GO111MODULE=on

install: true