language: go

sudo: false

matrix:
  include:
    - go: "1.10.x"
      script: go get . && go test -v ./...
    - go: "1.11.x"
      script: go mod vendor && go test -v -mod=vendor ./...
    - go: "1.12.x"
      script: go mod vendor && go test -v -mod=vendor ./...

env:
  - GO111MODULE=on

install: true
before_script:
  - go get github.com/smartystreets/goconvey/convey
